language: java

sudo: false # faster builds

script:
  - mvn test
  - mvn org.pitest:pitest-maven:mutationCoverage
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
